POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Northern Wildflowers",
    "author": "Jenny Fortier",
    "url": "https://northernwildflowers.ca/",
    "likes": 30
}